import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/Navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const seoulNamsan = localFont({
  src: [
    {
      path: "./fonts/seoulNamsanvert.ttf",
      weight: "100",
    },
    {
      path: "./fonts/seoulNamsanM.ttf",
      weight: "300",
    },
    {
      path: "./fonts/seoulNamsanL.ttf",
      weight: "500",
    },
    {
      path: "./fonts/seoulNamsanEB.ttf",
      weight: "700",
    },
    {
      path: "./fonts/seoulNamsanB.ttf",
      weight: "900",
    },
  ],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-screen h-screen">
      <body className={`${seoulNamsan.variable} antialiased w-full h-full`}>
        <main className="relative container mx-auto max-w-xs h-full m-0">
          {children}
        </main>
        <Navigation />
      </body>
    </html>
  );
}
